apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
rules:
- apiGroups: [""] # "" indicated the core API group
  verbs: ["get", "watch", "list"] # Action can be performed 
  resources: ["pods", "pods/log"] # 
